export const STRINGS = {
  // Login
  loginTitle: 'Login',
  emailLabel: 'E-mail',
  emailPlaceholder: 'Enter e-mail:',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter password:',
  loginButtonText: 'Login',
  loginHeader: 'Login',
  registerAccountText: 'If you do not have an account, you can',
  registerLinkText: 'register.',
  loginSuccessHeader: 'SUCCESS! NOW YOU CAN TO',
  loginSuccessSubheader: 'LOGIN',

  // Registration
  registrationHeader: 'Registration',
  nameLabel: 'Name',
  namePlaceholder: 'Enter name:',
  registrationButtonText: 'Registration',
  loginLinkText: 'login.',
  existingEmailError: 'Email already exists',
  nameRequiredError: 'Name is required',
  passwordRequiredError: 'Password is required',
  shortPasswordError: 'Password must be at least 6 characters.',
  registrationError: 'Registration error',
  registrationSuccessMessage: 'SUCCESS! NOW YOU CAN TO',
  emailRequiredError: 'Email is required',
  invalidEmailError: 'Invalid email format',

  // Course
  createCourseButtonText: 'CREATE COURSE',
  createCourseButtonAuthorText: 'CREATE AUTHOR',
  addButtonText: 'ADD',
  deleteButtonText: 'DELETE',
  searchButtonText: 'SEARCH',
  logoutButtonText: 'LOGOUT',
  createAddNewCourseButtonText: 'ADD NEW COURSE',
  showCourseButtonText: 'SHOW COURSE',
  searchPlaceholder: 'Enter course name:',
  titlePlaceholder: 'Enter title:',
  descriptionPlaceholder: 'Enter description:',
  authorNamePlaceholder: 'Enter author name:',
  durationPlaceholder: 'Enter duration in minutes:',
  titleLabel: 'Title',
  descriptionLabel: 'Description',
  authorNameLabel: 'Author name',
  durationLabel: 'Duration',
}
